services:
  - type: web
    name: aiapply-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
    rootDir: backend  # <--- THIS tells Render to look in backend/

